name: Triggered Workflow

on:
  workflow_call:
    inputs:
      CAPABILITY_NAME:
        required: true
        type: string
      AWS_ENVIRONMENT:
        required: true
        type: string
        default: prod
jobs:
  process_inputs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Display Inputs
        run: |
          echo "Input CAPABILITY_NAME is: ${{ input.CAPABILITY_NAME }}"
          echo "Input ENVIRONMENT is: ${{ input.AWS_ENVIRONMENT }}"
