name: Source Workflow

on:
  workflow_dispatch:
    inputs:
      HELM_RELEASE:
        description: 'Description for parameter 1'
        required: true
        default: 'cicd-test-capability'
      AWS_ENVIRONMENT:
        description: 'Description for parameter 2'
        required: false
        default: 'prod'

jobs:
  trigger_workflow:
    if: ${{ inputs.AWS_ENVIRONMENT == 'prod' || inputs.AWS_ENVIRONMENT == 'production'}}
    uses: gh-actions-riju/course-code/.github/workflows/triggered-workflow.yaml@main
    with:
     HELM_RELEASE: ${{ inputs.HELM_RELEASE }}
     AWS_ENVIRONMENT: ${{ inputs.AWS_ENVIRONMENT }}
