name: checkout
on: [push]

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: List files
        run: ls -lart
      - name: checkout
        run: |
          git init
          git remote add origin ""https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"
          git fetch origin
          git checkout master
      - name: list files after checkout
        run: ls -lart
