name: Source Workflow

on:
  workflow_dispatch:
    inputs:
      HELM_RELEASE:
        description: 'Description for parameter 1'
        required: true
        default: 'cicd-test-capability'
      AWS_ENVIRONMENT:
        description: 'Description for parameter 2'
        required: false
        default: 'prod'

jobs:
  trigger_workflow:
    if: ${{ inputs.AWS_ENVIRONMENT == 'prod' || inputs.AWS_ENVIRONMENT == 'production'}}
  
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Another Workflow
        uses: gh-actions-riju/course-code/.github/workflows/triggered-workflow.yaml@main
        with:
          inputs: |
            CAPABILITY_NAME: ${{ inputs.HELM_RELEASE }}
            ENVIRONMENT: ${{ inputs.AWS_ENVIRONMENT }}
