name: Triggered Workflow

on:
  workflow_call:
    
jobs:
  process_inputs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Display Inputs
        run: |
          echo "Input CAPABILITY_NAME is: ${{ input.HELM_RELEASE }}"
          echo "Input ENVIRONMENT is: ${{ env.AWS_ENVIRONMENT }}"
