name: working directories and shells
on: [push]
jobs:
  display-wd-info:
    runs-on: ubuntu-latest
    steps:
      - name: pwd
        run: |
          pwd
          ls -lart
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
  display-wd-info-windows:
    runs-on: windows-latest
    steps:
      - name: pwd
        run: |
          pwd
          ls -art
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
